package com.lexwilliam.core.navigation

object Screen {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val SIGN_UP = "sign_up"
    const val FORGOT_PASSWORD = "forgot_password"
    const val INVENTORY = "inventory"
    const val SUPPLIER = "supplier"
    const val PRODUCT_FORM = "product_form"
    const val PRODUCT_DETAIL = "product_detail"
    const val CATEGORY = "category"
    const val COMPANY_SEARCH = "company_search"
    const val COMPANY_FORM = "company_form"
    const val BARCODE = "barcode"
    const val HOME = "home"
    const val ORDER = "order"
    const val CART = "cart"
    const val CHECK_OUT = "check_out"
    const val TRANSACTION_DETAIL = "transaction_detail"
    const val TRANSACTION_HISTORY = "transaction_history"
    const val PROFILE = "profile"
    const val PAYMENT = "payment"
    const val DISCOUNT = "discount"
    const val TAX = "tax"
    const val FEE = "fee"
}